import { AppConfig, Module } from '@/types'

export const DEFAULT_MODULES: Module[] = [
  {
    id: 'routine',
    name: 'routine',
    label: 'Ma journée',
    description: 'Routine visuelle étape par étape',
    icon: '📋',
    enabled: false,
    locked: true,
    order: 0,
  },
  {
    id: 'reminders',
    name: 'reminders',
    label: 'Rappels',
    description: 'Médicaments, repas, tâches récurrentes',
    icon: '🔔',
    enabled: false,
    locked: true,
    order: 1,
  },
  {
    id: 'agenda',
    name: 'agenda',
    label: 'Agenda',
    description: 'Calendrier simplifié',
    icon: '📅',
    enabled: false,
    locked: true,
    order: 2,
  },
  {
    id: 'contacts',
    name: 'contacts',
    label: 'Contacts',
    description: "Contacts d'urgence en un clic",
    icon: '📞',
    enabled: false,
    locked: true,
    order: 3,
  },
  {
    id: 'aidants',
    name: 'aidants',
    label: 'Mes aidants',
    description: 'Société, intervenants et planning',
    icon: '🤝',
    enabled: false,
    locked: true,
    order: 4,
  },
  {
    id: 'services',
    name: 'services',
    label: 'Services utiles',
    description: 'CAF, CPAM, impôts, santé…',
    icon: '🔗',
    enabled: false,
    locked: true,
    order: 5,
  },
  {
    id: 'finances',
    name: 'finances',
    label: 'Finances',
    description: 'Budget quotidien simplifié',
    icon: '💶',
    enabled: false,
    locked: true,
    order: 6,
  },
]

export const DEFAULT_CONFIG: AppConfig = {
  userName: 'Mon proche',
  primaryColor: '#6366f1',
  backgroundColor: '#f9fafb',
  adminPassword: '1234',
  modules: DEFAULT_MODULES,
}
